INSERT IGNORE INTO ranks (rankid, rank_name, rank_score, badge) VALUES (1, 'Bronze', 0, '🥉');
INSERT IGNORE INTO ranks (rankid, rank_name, rank_score, badge) VALUES (2, 'Silver', 1500, '🥈');
INSERT IGNORE INTO ranks (rankid, rank_name, rank_score, badge) VALUES (3, 'Gold', 3000, '🥇');
INSERT IGNORE INTO ranks (rankid, rank_name, rank_score, badge) VALUES (4, 'Platinum', 6000, '💎');
INSERT IGNORE INTO game (gameid, title, genre, max_players, release_date) VALUES (1, 'Space Invaders', 'Arcade', 2, '2020-05-10');
INSERT IGNORE INTO game (gameid, title, genre, max_players, release_date) VALUES (2, 'Battle Arena', 'Action', 10, '2022-11-20');
INSERT IGNORE INTO achievement (achievementid, name, description, criteria_type, criteria_value) VALUES (1, 'First Blood', 'Win your first game', 'wins', 1);
INSERT IGNORE INTO achievement (achievementid, name, description, criteria_type, criteria_value) VALUES (2, 'Rising Champion', 'Win 3 games', 'wins', 3);
INSERT IGNORE INTO achievement (achievementid, name, description, criteria_type, criteria_value) VALUES (3, 'Arcade Veteran', 'Play 5 games', 'gamesPlayed', 5);
INSERT IGNORE INTO achievement (achievementid, name, description, criteria_type, criteria_value) VALUES (4, 'High Scorer', 'Reach 3000 points', 'totalScore', 3000);
INSERT IGNORE INTO item (itemid, item_name, item_type, rarity, bonus_score, bonus_wins, consumable) VALUES (1, 'Golden Sword', 'Weapon', 'Epic', 1500, 0, FALSE);
INSERT IGNORE INTO item (itemid, item_name, item_type, rarity, bonus_score, bonus_wins, consumable) VALUES (2, 'Health Potion', 'Consumable', 'Common', 500, 0, TRUE);
INSERT IGNORE INTO item (itemid, item_name, item_type, rarity, bonus_score, bonus_wins, consumable) VALUES (3, 'Victory Charm', 'Accessory', 'Rare', 300, 1, TRUE);
